Basic model created
FabLabSiegen/Lab-Manager pull request #12
Opened 2022-08-31 13:37 UTC by shahrier1995

the below model created :-1:

- Briefing
- FabLabUser
- Machine
- PowerPlug

2022-08-31 16:15 UTC, d-amend requested changes
see my comments

2022-08-31 16:15 UTC, d-amend commented on django/fablab/labmanager/models.py
>  from django.db import models
Please change all the verbose_name fields to those that fit the purpose written in the Django docs:

"A human-readable name for the object, singular:"
source: https://docs.djangoproject.com/en/4.1/ref/models/options/

Also please add comments to those fields, where it is not 100% clear, what they mean

2022-08-31 19:17 UTC, shahrier1995 commented on django/fablab/labmanager/models.py
> +    users = models.ManyToManyField(FabLabUser, blank=True, verbose_name='Assigned users', related_name='machines')
users = List of users that can use this machine.

2022-08-31 19:18 UTC, shahrier1995 commented
All comments resolved

2022-09-01 12:47 UTC, d-amend requested changes

2022-09-01 12:47 UTC, d-amend commented on django/fablab/labmanager/migrations/0001_initial.py
> +# Generated by Django 3.2.13 on 2022-08-23 19:52
Now we have migrations that add the fields and then remove them again. Could you clean that up? Because the model was never productive with those changes I would like to have it clean

2022-09-01 21:40 UTC, shahrier1995 commented on django/fablab/labmanager/migrations/0001_initial.py
> +# Generated by Django 3.2.13 on 2022-08-23 19:52
done.

2022-09-22 14:44 UTC, closed without merging